name: 'weather_data'
version: '1.0.0'

profile: 'weather_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_data:
    Bronze:
      +materialized: table
      +schema: Bronze
    Staging:
      +materialized: view
      +schema: Staging
    mart:
      +materialized: view
      +schema: Mart
      +python_version: "3.10"