create OR REPLACE warehouse WEATHER_WH
WITH WAREHOUSE_SIZE='X-SMALL'
AUTO_RESUME = TRUE
AUTO_SUSPEND = 30
INITIALLY_SUSPENDED= TRUE;

CREATE DATABASE WEATHER;

CREATE ROLE WEATHER_ROLE;

SELECT CURRENT_REGION();

CREATE SCHEMA WEATHER.RAW;

CREATE SCHEMA WEATHER.BRONZE;
WEATHER.MART
CREATE SCHEMA WEATHER.STAGING;

CREATE SCHEMA WEATHER.MART;

USE WAREHOUSE WEATHER_WH;

GRANT USAGE ON WAREHOUSE WEATHER_WH TO ROLE WEATHER_ROLE;
GRANT OPERATE ON WAREHOUSE WEATHER_WH TO ROLE WEATHER_ROLE;


drop table RAW.DIM_CITY;
DROP TABLE RAW.FCT_WEATHER_OBSERVATIONS;

GRANT USAGE ON DATABASE WEATHER TO ROLE WEATHER_ROLE;

GRANT ALL ON ALL SCHEMAS IN DATABASE WEATHER TO ROLE WEATHER_ROLE;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE WEATHER TO ROLE WEATHER_ROLE;





SELECT CURRENT_USER(),
       CURRENT_ROLE(),
       CURRENT_WAREHOUSE(),
       CURRENT_DATABASE();



GRANT ROLE WEATHER_ROLE TO USER SSAHANI;

SELECT * FROM MART.FCT_WEATHER_OBSERVATIONS;

select * from weather_comfort_scores;

select * from date_wise_observation;

select * from mart_daily_city_metrics;