
CREATE WAREHOUSE NETFLIX_WH
with
WAREHOUSE_SIZE='X-SMALL'
AUTO_RESUME=TRUE
AUTO_SUSPEND=10
INITIALLY_SUSPENDED=TRUE;


CREATE DATABASE NETFLIX;

CREATE SCHEMA NETFLIX.RAW;
CREATE SCHEMA NETFLIX.STAGING;
CREATE SCHEMA NETFLIX.MART;

CREATE ROLE NETFLIX_ROLE;

GRANT USAGE ON warehouse NETFLIX_WH TO ROLE NETFLIX_ROLE;

GRANT OPERATE ON warehouse NETFLIX_WH TO ROLE NETFLIX_ROLE;

GRANT ALL ON DATABASE NETFLIX TO ROLE NETFLIX_ROLE;

GRANT ALL ON ALL SCHEMAS IN DATABASE NETFLIX TO ROLE NETFLIX_ROLE;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE NETFLIX TO ROLE NETFLIX_ROLE;

GRANT ALL ON FUTURE TABLES IN DATABASE NETFLIX TO ROLE NETFLIX_ROLE;

GRANT ALL ON FUTURE VIEWS IN DATABASE NETFLIX TO ROLE NETFLIX_ROLE;

SET my_user=CURRENT_USER();

GRANT ROLE NETFLIX_ROLE TO USER IDENTIFIER($MY_USER);
