-- Set up Netflix external stage with S3 storage integration
-- Co-authored with CoCo
USE ROLE ACCOUNTADMIN;
USE DATABASE NETFLIX;
USE WAREHOUSE NETFLIX_WH;
USE SCHEMA NETFLIX.RAW;

CREATE OR REPLACE STORAGE INTEGRATION netflix_s3_int
TYPE=EXTERNAL_STAGE
STORAGE_PROVIDER='S3'
ENABLED=TRUE
STORAGE_AWS_ROLE_ARN='arn:aws:iam::381061952291:role/snowflake_s3_role'
STORAGE_ALLOWED_LOCATIONS=('s3://netflix-data-engineering-aug2026/');

GRANT USAGE ON INTEGRATION netflix_s3_int TO ROLE NETFLIX_ROLE;

GRANT CREATE FILE FORMAT ON SCHEMA NETFLIX.RAW TO ROLE NETFLIX_ROLE;

CREATE OR REPLACE FILE FORMAT NETFIX_DATA_FMT
TYPE ='CSV'
COMPRESSION='AUTO'
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
EMPTY_FIELD_AS_NULL=TRUE
TRIM_SPACE=FALSE;


CREATE OR REPLACE STAGE NETFLIX.RAW.NETFLIX_STAGE
URL='s3://netflix-data-engineering-aug2026'
STORAGE_INTEGRATION=netflix_s3_int
FILE_FORMAT='NETFIX_DATA_FMT';


DESC INTEGRATION netflix_s3_int;

list @NETFLIX_STAGE;

