USE DATABASE NETFLIX;
USE WAREHOUSE NETFLIX_WH;
USE SCHEMA NETFLIX.RAW;

list @NETFLIX_STAGE;

COPY INTO NETFLIX.RAW.R_MOVIES
FROM @NETFLIX_STAGE/movies.csv
FILE_FORMAT = NETFIX_DATA_FMT;

SELECT * FROM R_MOVIES LIMIT 20;

COPY INTO NETFLIX.RAW.R_RATINGS
FROM @NETFLIX_STAGE/ratings.csv
file_format= NETFIX_DATA_FMT;

SELECT * FROM NETFLIX.RAW.R_RATINGS LIMIT 10;

COPY INTO NETFLIX.RAW.r_genome_tags
FROM @NETFLIX_STAGE/genome-tags.csv
FILE_FORMAT=NETFIX_DATA_FMT;

select * from r_genome_tags limit 10000000;

COPY INTO NETFLIX.RAW.r_genome_scores
FROM @NETFLIX_STAGE/genome-scores.csv
FILE_FORMAT=NETFIX_DATA_FMT;

select * from r_genome_scores limit 100000;

select
    movieid,
    RATING,
    RATING_TIMESTAMP,
    EXTRACT(MONTH FROM RATING_TIMESTAMP) AS RATING_MONTH
    FROM NETFLIX.RAW.R_RATINGSNETFLIX.MART.MART_R_RATINGS LIMIT 10;

COPY INTO NETFLIX.RAW.R_TAGS
FROM @NETFLIX_STAGE/tags.csv
FILE_FORMAT = NETFIX_DATA_FMT
ON_ERROR=CONTINUE;

select * from r_tags limit 10;
SELECT *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  'NETFLIX.RAW.R_TAGS',
  DATEADD('hour', -24, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;



ALTER USER SSAHANI
SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6A+IpLGCfiFFJL9uHJ1T
HbGzLgM8AlaPvt+Od/8KOSBxYQ5LOoTkyEbTStDmJivPrq+lvRrbhGCVlmVWBChn
pw6NeTInVftzde8bTEZBMJrYkwOsApDrEyFL+lRTHQ4rfDh2TykH9CSyyYNfLAiq
xsbbucJVhGx74T3gCIE2Uqn7j8zhACKx3rn63e/039SMPJl3S3n3Y2ehwjujBWMG
/6c6b06QaLc+4AAO1W8MTjn5IAH55JPMaJ9jZVHd3SjbYqx/BfEAFdALIb2cJ2+8
CheAY8gHRY3urhmE9dsc07YxlVeoBsB/8j99cIQ1Pb1e6928AOPVX/sNptLe23P+
owIDAQAB';



select NETFLIX.RAW.NETFLIX_STAGEMOVIEID,
       title,
       regexp_replace(title,'[0-9()]+',''),
       regexpNETFLIX.MARTNETFLIX.MART_substr(title,'[0-9]+'),
       genres,
       regexp_count(genres,'[|]')+1
from NETFLIX.RAW.R_MOVIES;

show views in schema NETFLIX.STAGING;
show views in schema NETFLIX.MART;


SHOW TABLES IN SCHEMA NETFLIX.RAW_BRONZE;
SHOW VIEWS IN SCHEMA NETFLIX.STAGING;
SHOW VIEWS IN SCHEMA NETFLIX.MART;


drop schema NETFLIX.RAW_BRONZE;
drop schema NETFLIX.RAW_STAGING;
drop schema NETFLIX.RAW_MART;


SELECT * FROM NETFLIX.MART.MART_R_MOVIES where RELEASE_YEAR IS NULL;NETFLIX.MART