{{config(schema= 'Mart')}}

WITH panel_data AS (
    SELECT
        TO_CHAR(INTERVIEW_DATE, 'MON-YYYY') AS INTERVIEW_MONTH,
        PANELIST_NAME,
        EMAIL_ID,
        SUM(
            CASE
                WHEN AVAILABILITY_CATEGORY IN ('AVAILABLE','TENTATIVE')
                THEN 1
                ELSE 0
            END
        ) AS TOTAL_AVAILABILITY
    FROM {{ ref('stg_PANEL_AVAILABILITY') }}
    GROUP BY 1, 2, 3
),

fp_data AS (
    SELECT
        INTERVIEW_MONTH,
        PANEL_EMAIL_ID,
        PANEL_NAME,
        NUMBER_OF_INTERVIEWS
    FROM {{ ref('fact_panel_performance') }} fp,
),
panel_master AS (
SELECT *
FROM {{ ref('dim_panels') }}
)
SELECT DISTINCT
COALESCE(pa.INTERVIEW_MONTH, fp.INTERVIEW_MONTH) AS INTERVIEW_MONTH,
COALESCE(
pa.PANELIST_NAME,
pm.PANELIST_NAME,
fp.PANEL_NAME
) AS PANEL_NAME,
NVL(pa.TOTAL_AVAILABILITY,0) AS TOTAL_AVAILABILITY,
NVL(fp.NUMBER_OF_INTERVIEWS,0) AS NUMBER_OF_INTERVIEWS
FROM panel_data pa
FULL JOIN fp_data fp
ON pa.INTERVIEW_MONTH = fp.INTERVIEW_MONTH
AND UPPER(TRIM(pa.EMAIL_ID)) = UPPER(TRIM(fp.PANEL_EMAIL_ID))
LEFT JOIN panel_master pm
ON UPPER(TRIM(fp.PANEL_EMAIL_ID)) = pm.EMAIL_ID

-- SELECT
--     COALESCE(pa.INTERVIEW_MONTH, fp.INTERVIEW_MONTH) AS INTERVIEW_MONTH,
--     pa.EMAIL_ID PA_EMAIL_ID, fp.PANEL_EMAIL_ID INT_EMAIL_ID,
--     -- COALESCE(pa.PANELIST_NAME, fp.PANEL_EMAIL_ID, 'Unknown') AS PANEL_NAME,
--     NVL(pa.TOTAL_AVAILABILITY, 0) AS TOTAL_AVAILABILITY,
--     NVL(fp.NUMBER_OF_INTERVIEWS, 0) AS NUMBER_OF_INTERVIEWS -- Removed trailing comma here
-- FROM panel_data pa
-- FULL JOIN fp_data fp
--     ON pa.INTERVIEW_MONTH = fp.INTERVIEW_MONTH
--     AND pa.EMAIL_ID = fp.PANEL_EMAIL_ID