{{config(schema= 'Mart')}}

WITH latest_interview AS (
SELECT *
FROM {{ ref('stg_INTERVIEW_PANEL_DATA')}}
QUALIFY ROW_NUMBER() OVER (
PARTITION BY CANDIDATE_EMAIL_ID
ORDER BY EVALUATION_DATE_TIME DESC
) = 1
)
select NVL(UPPER(PROFILE_SHARED_BY),'UNKNOWN') AS PROFILE_SHARED_BY, 
       COUNT(DISTINCT CANDIDATE_EMAIL_ID) PROFILE_SHARED,
       COUNT(DISTINCT CASE
        WHEN EVALUATION_DATE_TIME IS NOT NULL
        THEN CANDIDATE_EMAIL_ID
        END) AS L1_SCHEDULED,
        COUNT(DISTINCT CASE
        WHEN EVALUATION_DATE_TIME IS NOT NULL AND L1_STATUS IS NULL
        THEN CANDIDATE_EMAIL_ID
        END) AS L1_PENDING,
        COUNT(DISTINCT CASE
        WHEN EVALUATION_DATE_TIME IS NOT NULL AND UPPER(L1_STATUS)= 'SELECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS L1_CLEARED,
        COUNT(DISTINCT CASE
        WHEN UPPER(L1_STATUS) LIKE '%NO SHOW%'
          OR UPPER(L1_STATUS) LIKE '%CANCELLED%'
          OR UPPER(L1_STATUS) LIKE '%DIDNT JOIN%'
        THEN CANDIDATE_EMAIL_ID
        END) AS L1_NO_SHOW,
        COUNT(DISTINCT CASE
         WHEN UPPER(L2_STATUS) LIKE '%NO SHOW%'
         OR UPPER(L2_STATUS) LIKE '%CANCELLED%'
         OR UPPER(L2_STATUS) LIKE '%DIDNT JOIN%'
         THEN CANDIDATE_EMAIL_ID
         END) AS L2_NO_SHOW,

        COUNT(DISTINCT CASE
        WHEN EVALUATION_DATE_TIME IS NOT NULL AND UPPER(L2_STATUS)= 'SELECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS L2_CLEARED,
        COUNT(DISTINCT CASE
        WHEN EVALUATION_DATE_TIME IS NOT NULL AND UPPER(CUSTOMER_ROUND_STATUS)= 'SELECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS CUSTOMER_ROUND_CLEARED,
        COUNT(DISTINCT CASE
        WHEN UPPER(L1_STATUS) = 'REJECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS L1_REJECTED,
        COUNT(DISTINCT CASE
        WHEN UPPER(L2_STATUS) = 'REJECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS L2_REJECTED,
        COUNT(DISTINCT CASE
        WHEN UPPER(CUSTOMER_ROUND_STATUS) = 'REJECTED'
        THEN CANDIDATE_EMAIL_ID
        END) AS CUSTOMER_ROUND_REJECTED
        FROM latest_interview
        GROUP BY 1