{{config(materialized= 'incremental', 
          schema= 'Bronze',
          unique_key= 'INTERVIEW_KEY',
          incremental_strategy= 'merge')}}

WITH SOURCE_DATA AS (
SELECT
       trim(CANDIDATE_NAME) as CANDIDATE_NAME,
       trim(GROUP_NAME) as GROUP_NAME,
       trim(DEMAND) as DEMAND,
       EXPERIENCE_YEARS,
       TRY_TO_DECIMAL(
       REGEXP_SUBSTR(EXPERIENCE_YEARS, '[0-9.]+'),5,2) AS EXPERIENCE_YEARS_NUM,
       trim(PROFILE_SHARED_BY) as PROFILE_SHARED_BY,
       CONTACT_DETAILS,
       REGEXP_SUBSTR(CONTACT_DETAILS,'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9]+\\.[a-zA-Z]{2,}') as CANDIDATE_EMAIL_ID,
       REGEXP_SUBSTR(CONTACT_DETAILS,'\\+?[0-9][0-9\\s-]+{8,}') as CANNDIATE_MOBILE,
       TRY_TO_DATE(ASSIGNED_DATE,'DD-MM-YYYY') AS ASSIGNED_DATE,
       TRY_TO_DATE(EVALUATION_DATE_TIME,'DD-MM-YYYY') AS EVALUATION_DATE_TIME,
       TRIM(PANEL_NAME) AS PANEL_NAME,
       TRIM(L1_STATUS) AS L1_STATUS,
       TRIM(L2_STATUS) AS L2_STATUS,
       TRIM(CUSTOMER_ROUND_STATUS) AS CUSTOMER_ROUND_STATUS,
       TRIM(L1_FEEDBACK) AS L1_FEEDBACK,
       TRIM(L2_FEEDBACK) AS L2_FEEDBACK,
       COMMENTS,
       ACTION_ITEM
FROM {{ source('RAW','INTERVIEW_PANEL_DATA') }}),
FINAL AS (
SELECT
MD5(
COALESCE(CANDIDATE_EMAIL_ID,'') || '|' ||
COALESCE(TO_VARCHAR(ASSIGNED_DATE),'') || '|' ||
COALESCE(PANEL_NAME,'')
) AS INTERVIEW_KEY,*
FROM SOURCE_DATA)

SELECT * FROM FINAL

{% if is_incremental()%}
WHERE INTERVIEW_KEY NOT IN (SELECT INTERVIEW_KEY FROM {{this}})
{%endif%}