
drop SCHEMA ZOMATO_SCH;

CREATE WAREHOUSE ZOMATO_WH
WITH 
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;


CREATE DATABASE ZOMATO;

CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW;
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING;
CREATE SCHEMA IF NOT EXISTS ZOMATO.MARTS;

CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOTS;

CREATE SCHEMA  IF NOT EXISTS ZOMATO.AI;


CREATE ROLE IF NOT EXISTS DBT_ROLE;

GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;

GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;

GRANT ALL ON DATABASE ZOMATO TO ROLE DBT_ROLE;

GRANT ALL ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;


GRANT ALL ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;

GRANT ALL ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;



SET my_user=CURRENT_USER();

GRANT ROLE DBT_ROLE TO USER IDENTIFIER($MY_USER);



